-- dlc.lua — DLC config generation + per-game DLC overview.
--
-- Faithful Lua port of steamtools.py generate_dlc_config / get_dlc_overview.
-- Pulls the DLC list + names from the Steam Store API and cross-references the
-- installed .lua (addappid / setManifestid). Emits CreamAPI / SmokeAPI /
-- GreenLuma / CODEX configs.

local cjson       = require("json")
local m_utils     = require("utils")
local http_client = require("http_client")
local st          = require("st_util")

local M = {}

local STORE_API = "https://store.steampowered.com/api/appdetails?appids=%s&filters=basic"

-- Fetch appdetails "data" for one appid. Returns (data_table|nil, http_status).
local function fetch_appdetails(appid, timeout)
    local ok, resp = pcall(http_client.get, string.format(STORE_API, tostring(appid)), { timeout = timeout or 10 })
    if ok and resp and resp.status == 200 and resp.body then
        local ok2, parsed = pcall(cjson.decode, resp.body)
        if ok2 and type(parsed) == "table" then
            local entry = parsed[tostring(appid)]
            if type(entry) == "table" and entry.success ~= false and type(entry.data) == "table" then
                return entry.data, resp.status
            end
        end
        return nil, resp.status
    end
    return nil, (resp and resp.status) or 0
end

function M.generate_dlc_config(appid, format)
    appid = tonumber(appid)
    if not appid then return { success = false, error = "invalid appid" } end
    format = tostring(format or "creamapi")

    local ok, res = pcall(function()
        local data = fetch_appdetails(appid, 10)
        local app_name, dlc_ids
        if type(data) == "table" then
            app_name = data.name or ("AppID " .. appid)
            dlc_ids = type(data.dlc) == "table" and data.dlc or {}
        else
            app_name = "AppID " .. appid
            dlc_ids = {}
        end

        local dlc_list = {}
        local n = 0
        for _, dlc_id in ipairs(dlc_ids) do
            n = n + 1
            if n > 200 then break end
            local name = "DLC " .. tostring(dlc_id)
            local dd = fetch_appdetails(dlc_id, 5)
            if type(dd) == "table" and dd.name then name = dd.name end
            table.insert(dlc_list, { id = dlc_id, name = name })
            m_utils.sleep(100)
        end

        local content = st.read_lua_file(appid)
        local depot_ids = content and st.get_depot_ids_from_lua(content) or {}

        local fmt = format:lower()
        local config_text, filename = "", ""

        if fmt == "creamapi" then
            local lines = {
                "; " .. app_name, "; Generated by STLT - Rewired", "",
                "[steam]", "appid = " .. appid, "unlockall = false",
                "orgapi = steam_api_o.dll", "orgapi64 = steam_api64_o.dll", "",
                "[steam_misc]", "disableoverlay = false", "",
                "[dlc]",
            }
            for _, dlc in ipairs(dlc_list) do table.insert(lines, dlc.id .. " = " .. dlc.name) end
            config_text = table.concat(lines, "\n")
            filename = "cream_api.ini"
        elseif fmt == "smokeapi" then
            local dlc_map = {}
            for _, d in ipairs(dlc_list) do dlc_map[tostring(d.id)] = d.name end
            config_text = cjson.encode({ enabled = true, unlock_all = true, app_id = appid, dlc = dlc_map })
            filename = "config.json"
        elseif fmt == "greenluma" then
            local lines = { "// " .. app_name .. "  --  GreenLuma DLC list", "// " .. #dlc_list .. " DLCs" }
            for i, dlc in ipairs(dlc_list) do
                table.insert(lines, "// " .. i .. ". " .. dlc.name)
                table.insert(lines, tostring(dlc.id))
            end
            config_text = table.concat(lines, "\n")
            filename = "AppList.txt"
        elseif fmt == "codex" then
            local lines = {
                "; " .. app_name, "[Settings]", "AppId=" .. appid,
                "Language=english", "LowViolence=0", "", "[DLC]",
            }
            for _, dlc in ipairs(dlc_list) do table.insert(lines, dlc.id .. " = " .. dlc.name) end
            config_text = table.concat(lines, "\n")
            filename = "steam_emu.ini"
        end

        return {
            success = true, appid = appid, app_name = app_name, format = fmt,
            filename = filename, config = config_text,
            dlc_count = #dlc_list, depot_count = #depot_ids,
        }
    end)
    if not ok then return { success = false, error = tostring(res) } end
    return res
end

function M.get_dlc_overview(appid)
    appid = tonumber(appid)
    if not appid then return { success = false, error = "invalid appid" } end

    local data, status = fetch_appdetails(appid, 10)
    if data == nil then return { success = false, error = "Store API HTTP " .. tostring(status) } end
    local app_name = data.name or ("AppID " .. appid)
    local dlc_ids = type(data.dlc) == "table" and data.dlc or {}

    local content = st.read_lua_file(appid)
    local appids_in_lua, manifests_in_lua = {}, {}
    if content then
        for id in content:gmatch("addappid%s*%(%s*(%d+)") do appids_in_lua[tonumber(id)] = true end
        for id, mid in content:gmatch('setManifestid%s*%(%s*(%d+)%s*,%s*"?(%d+)') do
            manifests_in_lua[tonumber(id)] = mid
        end
    end

    local dlc_entries, fetched_names, n = {}, 0, 0
    local known = {}
    for _, dlc_id in ipairs(dlc_ids) do
        known[dlc_id] = true
        n = n + 1
        if n > 200 then break end
        local name = "DLC " .. tostring(dlc_id)
        local dd = fetch_appdetails(dlc_id, 5)
        if type(dd) == "table" and dd.name then name = dd.name; fetched_names = fetched_names + 1 end
        m_utils.sleep(50)
        local in_lua = appids_in_lua[dlc_id] == true
        local has_manifest = manifests_in_lua[dlc_id] ~= nil
        table.insert(dlc_entries, {
            id = dlc_id, name = name, inLua = in_lua, hasManifest = has_manifest,
            manifestId = manifests_in_lua[dlc_id] or "",
            status = (in_lua and has_manifest) and "active"
                or (in_lua and "added_no_manifest" or "missing"),
        })
    end

    -- DLCs present in the .lua that the store doesn't list (orphans / private)
    for aid in pairs(appids_in_lua) do
        if not known[aid] and aid ~= appid then
            table.insert(dlc_entries, {
                id = aid, name = "(unknown depot/DLC " .. aid .. ")",
                inLua = true, hasManifest = manifests_in_lua[aid] ~= nil,
                manifestId = manifests_in_lua[aid] or "", status = "orphan",
            })
        end
    end

    local active, missing, orphans = 0, 0, 0
    for _, d in ipairs(dlc_entries) do
        if d.status == "active" then active = active + 1
        elseif d.status == "missing" then missing = missing + 1
        elseif d.status == "orphan" then orphans = orphans + 1 end
    end

    return {
        success = true, appid = appid, gameName = app_name,
        totalDlcs = #dlc_entries, active = active, missing = missing,
        orphans = orphans, namesFetched = fetched_names, dlcs = st.A(dlc_entries),
    }
end

-- One-click DLC unlock, the luatools-native way (no external steam_api hook / SmokeAPI DLL):
-- append `addappid(<dlc_id>)` for every store-listed DLC not already in the game's stplug-in lua,
-- so Steam grants ownership of the DLC on next launch. Backs the lua up first (reversible).
function M.unlock_all_dlc(appid)
    appid = tonumber(appid)
    if not appid then return { success = false, error = "invalid appid" } end

    local ok, res = pcall(function()
        local content, path = st.read_lua_file(appid)
        if not content or not path then
            return { success = false, error = "No stplug-in lua for this app — add the game first." }
        end

        local data = fetch_appdetails(appid, 10)
        local app_name = (type(data) == "table" and data.name) or ("AppID " .. appid)
        local dlc_ids = (type(data) == "table" and type(data.dlc) == "table") and data.dlc or {}
        if #dlc_ids == 0 then
            return { success = true, appid = appid, app_name = app_name, added = 0, already = 0,
                     message = "No DLC listed for this app on the store." }
        end

        -- appids already present in the lua (via addappid)
        local present = {}
        for id in content:gmatch("addappid%s*%(%s*(%d+)") do present[tonumber(id)] = true end

        local to_add, already = {}, 0
        for _, dlc_id in ipairs(dlc_ids) do
            local did = tonumber(dlc_id)
            if did then
                if present[did] then
                    already = already + 1
                else
                    to_add[#to_add + 1] = did
                    present[did] = true
                end
            end
        end

        if #to_add == 0 then
            return { success = true, appid = appid, app_name = app_name, added = 0, already = already,
                     message = "All " .. already .. " DLC already present in the lua." }
        end

        local backup = path .. ".bak-" .. st.stamp()
        m_utils.write_file(backup, content)

        local parts = { content }
        if not content:match("\n$") then parts[#parts + 1] = "\n" end
        parts[#parts + 1] = "-- DLC unlocked by STLT - Rewired\n"
        for _, did in ipairs(to_add) do
            parts[#parts + 1] = "addappid(" .. did .. ") -- DLC\n"
        end
        m_utils.write_file(path, table.concat(parts))

        return {
            success = true, appid = appid, app_name = app_name,
            added = #to_add, already = already, total_dlc = #dlc_ids, backup = backup,
            message = string.format("Unlocked %d DLC for %s (%d already present). Restart Steam to apply.",
                #to_add, app_name, already),
        }
    end)
    if not ok then return { success = false, error = tostring(res) } end
    return res
end

return M
